version: '3'

services:
  user-backend:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/yourname/.ssh
      - ..:/opt/yourname/code
    command: ["tail -f /dev/null"]
    ports:
      - 8123:8000
    depends_on:
      - db-for-user-backend
    # networks:
    #   - microservices-for-xxx

  db-for-user-backend:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    # networks:
    #   - microservices-for-xxx

# networks:
#   microservices-for-xxx:
#     external: true


